version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: business_analytics_db
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      POSTGRES_DB: business_analytics
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d/1_schema
      - ./data:/docker-entrypoint-initdb.d/2_data
