services:
  postgres:
    image: postgres:16
    container_name: business_analytics_db
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      POSTGRES_DB: business_analytics
    ports:
      - "5432:5432"
    volumes:
      - ./schema/01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./data/02_insert_sample_data.sql:/docker-entrypoint-initdb.d/02_insert_sample_data.sql
      - ./queries:/queries
